// flow-typed signature: a6d4ebf0299240d1b064bb274745d8ca
// flow-typed version: <<STUB>>/@types/react_v^16.3.12/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/react' {
  declare module.exports: any;
}
