// flow-typed signature: af8c88e0dce5cfdbd8579deb0ee77d03
// flow-typed version: <<STUB>>/jest-meteor-stubs_v^1.5.1/flow_v0.73.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-meteor-stubs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-meteor-stubs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-meteor-stubs/lib/meteor/accounts-base' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/alanning_roles' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/aldeed_simple-schema' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/check' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/http' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/mdg_validated-method' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/meteor' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/meteorhacks_picker' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/momentjs_moment' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/mongo' {
  declare module.exports: any;
}

declare module 'jest-meteor-stubs/lib/meteor/natestrauser_publish-performant-counts' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-meteor-stubs/lib/meteor/accounts-base.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/accounts-base'>;
}
declare module 'jest-meteor-stubs/lib/meteor/alanning_roles.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/alanning_roles'>;
}
declare module 'jest-meteor-stubs/lib/meteor/aldeed_simple-schema.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/aldeed_simple-schema'>;
}
declare module 'jest-meteor-stubs/lib/meteor/check.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/check'>;
}
declare module 'jest-meteor-stubs/lib/meteor/http.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/http'>;
}
declare module 'jest-meteor-stubs/lib/meteor/mdg_validated-method.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/mdg_validated-method'>;
}
declare module 'jest-meteor-stubs/lib/meteor/meteor.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/meteor'>;
}
declare module 'jest-meteor-stubs/lib/meteor/meteorhacks_picker.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/meteorhacks_picker'>;
}
declare module 'jest-meteor-stubs/lib/meteor/momentjs_moment.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/momentjs_moment'>;
}
declare module 'jest-meteor-stubs/lib/meteor/mongo.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/mongo'>;
}
declare module 'jest-meteor-stubs/lib/meteor/natestrauser_publish-performant-counts.js' {
  declare module.exports: $Exports<'jest-meteor-stubs/lib/meteor/natestrauser_publish-performant-counts'>;
}
